### ISSUE TITLE
Not rendering StarTrekker AM-modules

### ISSUE THREAD

**Issue by Ziphoid** [emoon/stemgen#4]
Nothing is rendered when using such a module for input. It probably has to do with that it seems to need the accompanying `<filname>.nt` file loaded as well. OpenMPT can load the module and XMP can play it.
https://modland.com/pub/modules/Startrekker%20AM/

**Comment by emoon** [comment]
Turns out this isn't supported in libopenmpt https://bugs.openmpt.org/view.php?id=925

**Comment by Ziphoid** [comment]
It's not a big deal either, so let's just close it, I guess. :)
