### ISSUE TITLE
FLAC-output is not 100% valid

### ISSUE THREAD

**Issue by Ziphoid** [emoon/stemgen#7]
It seems like the `--write flac` render does something wrong, because the file does not work everywhere. It can be read by Reaper and Sound Studio, but gives an error in Fission and is refused to play by the macOS preview player.

![CleanShot 2023-11-21 at 13 39 56@2x](https://github.com/emoon/stemgen/assets/138041/20d6d2a0-9b0c-4b5b-acff-090b5b903fbe)

**Comment by emoon** [comment]
16-bit output or floats (or both)?

**Comment by Ziphoid** [comment]
Both.

**Comment by emoon** [comment]
I tested with audacity and vlc and they didn't report any issues so I assumed it was fine 🤔

**Comment by Ziphoid** [comment]
Yeah, not even the flac tool reports any problem, interestingly enough. Try playing with preview on macOS. I use Sonoma, btw.
