### ISSUE TITLE
Feature request: Full-only render

### ISSUE THREAD

**Issue by Ziphoid** [emoon/stemgen#8]
Sometimes, it'd be good to be able to only render a full version of the module, without any instrument renders.

**Comment by emoon** [comment]
Maybe it would make sense to add a `--instruments` to be supplied when you want to render the instruments then. So if only `--full` is there only the whole song will be rendered, but if `--channels` is there it will implicitly assume `--instruments` as well.

**Comment by Ziphoid** [comment]
That sounds like a good way to do it.
